services:
  - type: web
    name: python-portfolio
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn python_portfolio.wsgi:application
    autoDeploy: true
    envVars:
      - key: DJANGO_SECRET_KEY
        value: django-insecure-s2w3sjw_8pjp1f-67!sx(vzoj_pdwmr*v2!v6)p-)_m9fn^u=^
      - key: DEBUG
        value: false
